# Generated by Django 6.0.6 on 2026-06-28 21:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('username', models.CharField(blank=True, help_text='Optional username.', max_length=150, null=True)),
                ('email', models.EmailField(help_text='Email address (must be unique).', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='User profile image.', null=True, upload_to='profile_images/')),
                ('date_of_birth', models.DateField(blank=True, help_text='User date of birth.', null=True)),
                ('address', models.TextField(blank=True, help_text='User address.', null=True)),
                ('city', models.CharField(blank=True, help_text='City name.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province name.', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country name.', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code.', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this record is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('email', models.EmailField(help_text='Email used for login attempt.', max_length=254)),
                ('status', models.CharField(choices=[('success', 'Successful Login'), ('failed', 'Failed Login Attempt'), ('logout', 'Logout'), ('timeout', 'Session Timeout')], default='success', help_text='Login status.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the login attempt.')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the browser.', null=True)),
                ('device_type', models.CharField(blank=True, help_text='Device type (e.g., Mobile, Desktop, Tablet).', max_length=50, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='Time of login attempt.')),
                ('logout_time', models.DateTimeField(blank=True, help_text='Time of logout.', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login attempt.', max_length=255, null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Duration of the user session.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user (null for failed login attempts).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this record is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('code', models.CharField(help_text='Permission code (e.g., view_user, create_course). Should be unique.', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows.', null=True)),
                ('category', models.CharField(default='general', help_text='Permission category (e.g., user_management, academic, finance).', max_length=100)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission',
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['code'], name='permission_code_91d4d6_idx'), models.Index(fields=['category'], name='permission_categor_593940_idx'), models.Index(fields=['is_active'], name='permission_is_acti_50c675_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this record is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('name', models.CharField(help_text='Role name (e.g., Admin, Teacher, Student).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its responsibilities.', null=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted. True for built-in roles.')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='role_name_796487_idx'), models.Index(fields=['is_active'], name='role_is_acti_d578e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this record is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('permission', models.ForeignKey(help_text='The permission.', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(help_text='The role.', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permission',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique identifier.', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this record is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the role was assigned.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The admin who assigned this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='The role.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(help_text='The user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_role',
                'ordering': ['user', 'role'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_acti_7f3bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_693b68_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-login_time'], name='login_histo_user_id_c59338_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email', '-login_time'], name='login_histo_email_45c0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['status'], name='login_histo_status_c9661d_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='role_permis_role_id_f4f546_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['is_active'], name='role_permis_is_acti_9c460a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='user_role_user_id_1d88a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['is_active'], name='user_role_is_acti_1bea02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
